# Generated by Django 5.0.4 on 2024-04-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_category_active_category_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tours.category'),
        ),
    ]
