# Generated by Django 5.0.4 on 2024-04-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_decription_tour_description_tour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tour/name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='price_adult',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_kid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_service',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tours.place'),
        ),
    ]
