# Generated by Django 5.0.4 on 2024-04-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_place_tour_price_adult_tour_price_kid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tours.tour'),
        ),
    ]
