# Generated by Django 5.0.4 on 2024-04-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tour_place_place_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(to='tours.place'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_kid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
