# Generated by Django 5.0.4 on 2024-04-23 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_place_tour_tour_place_alter_tour_price_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
