# Generated by Django 5.0.4 on 2024-05-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='tour',
            field=models.ManyToManyField(to='tours.tour'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tours.category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='option',
            field=models.CharField(choices=[('A', 'Vé người lớn'), ('B', 'Vé trẻ em')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='Place/name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
