# Generated by Django 5.0.4 on 2024-05-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_remove_tour_place_place_tour_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(related_name='places_tours', to='tours.place'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='tour',
        ),
        migrations.AddField(
            model_name='place',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places_tours', to='tours.tour'),
        ),
    ]
