# Generated by Django 5.0.4 on 2024-05-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tour_place_remove_place_tour_place_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tour',
        ),
    ]
