# Generated by Django 5.0.4 on 2024-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_remove_place_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tours',
            field=models.ManyToManyField(related_name='places_tours', to='tours.tour'),
        ),
    ]
