# Generated by Django 5.0.4 on 2024-05-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_place_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
    ]
