# Generated by Django 5.0.4 on 2024-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_remove_tour_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tours',
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(related_name='places_tours', to='tours.place'),
        ),
    ]
