# Generated by Django 5.0.4 on 2024-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_remove_place_tours_tour_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_arrive',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_depart',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_arrive',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_depart',
            field=models.TimeField(null=True),
        ),
    ]
