# Generated by Django 5.0.4 on 2024-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_remove_ticket_time_arrive_remove_ticket_time_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='Tours/name'),
        ),
    ]
