# Generated by Django 5.0.4 on 2024-05-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_ticket_booking_date_ticket_user_tour_arrival_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
