# Generated by Django 5.0.4 on 2024-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_commentinnew_commentintour_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='author',
        ),
        migrations.AlterField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'new')},
        ),
    ]
