# Generated by Django 5.0.4 on 2024-05-09 13:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_customer_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imagesOfPlace'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imagesOfTour'),
        ),
    ]
