# Generated by Django 5.0.4 on 2024-05-19 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_admin_remove_customer_is_customer_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date_arrival',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='date_depart',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=1)),
                ('kids', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.customer')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
