# Generated by Django 5.0.4 on 2024-05-19 09:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_tour_date_arrival_tour_date_depart_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='new',
            name='date_post',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imagesOfNew'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(),
        ),
    ]
