# Generated by Django 5.0.4 on 2024-05-19 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0030_alter_new_author_alter_rating_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='arrival',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='departure',
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
