# Generated by Django 5.0.4 on 2024-05-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0031_rename_arrival_tour_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='date_arrival',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='date_depart',
        ),
    ]
