# Generated by Django 5.0.4 on 2024-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0032_remove_tour_date_arrival_remove_tour_date_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
