# Generated by Django 5.0.4 on 2024-05-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0033_tour_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
