# Generated by Django 5.0.4 on 2024-05-20 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0034_remove_ticket_booking_date_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_arrive',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='issued',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_arrive',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_depart',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tours.booking'),
        ),
    ]
